/**
 * PulseEngineRN — React Native audio engine + state machine.
 *
 * Mirrors the public surface of `@pulse-music/core` `PulseEngine` so the
 * RN renderer + the `usePulseAudioRN` hook can be drop-in equivalents
 * of their web counterparts, but uses `expo-av` Audio.Sound for playback
 * since RN has no HTMLAudioElement / AudioContext.
 *
 * Design notes:
 *
 *   - Singleton instance per app (lazy `getSharedEngineRN()`). Mirrors
 *     the web's `engine-singleton` pattern so playback survives screen
 *     navigations + the FAB is a thin overlay over the inline card.
 *   - State updates fan out via `onStateChange(cb)` subscribers (same
 *     contract as web). The `usePulseAudioRN` hook bridges into React
 *     state via `useSyncExternalStore`.
 *   - Typed event bus: 'play' / 'pause' / 'trackchange' / 'error'.
 *   - Pseudo-FFT (`eqBars`) is generated by a 60 Hz `setInterval` while
 *     playing. RN doesn't expose AnalyserNode from expo-av in v16; the
 *     subsequent rc patches will swap to `react-native-audio-api` for
 *     real FFT when Swansion ships stable iOS support.
 *   - Error reasons mirror the web: 'play-rejected' | 'media-error' | 'stalled'.
 *
 * Public surface kept identical to PulseEngine where possible so
 * future code-sharing remains practical.
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — expo-av is a peer dep; consumer installs it
import { Audio, type AVPlaybackStatus } from 'expo-av'

import type {
  AudioEvent,
  ErrorReason,
  EventListener,
  EventMap,
  PulseState,
  Track,
  Unsubscribe,
} from '@pulse-music/types'

const DEFAULT_TRACKS: Track[] = [
  {
    title: 'MIDNIGHT RUN',
    src: 'https://yamadablog.github.io/pulse-player/audio/track1.webm',
    cover: 'https://yamadablog.github.io/pulse-player/audio/cover.webp',
  },
  {
    title: 'DEEP FOCUS',
    src: 'https://yamadablog.github.io/pulse-player/audio/track2.webm',
    cover: 'https://yamadablog.github.io/pulse-player/audio/cover2.webp',
  },
]

function createInitialState(): PulseState {
  return {
    currentTrack: 0,
    isPlaying: false,
    currentTime: 0,
    duration: 0,
    isVisible: false,
    hasBeenOpened: false,
    ambientEq: false,
    playCount: 0,
    pauseCount: 0,
    trackChangeCount: 0,
  }
}

type StateListener = (state: Readonly<PulseState>) => void

export class PulseEngineRN {
  private _state: PulseState = createInitialState()
  private _tracks: Track[]
  private _eqBars: number[] = [0, 0, 0, 0]
  private _eqAmbientBars: number[] = new Array(32).fill(0)

  private sound: Audio.Sound | null = null
  private eqInterval: ReturnType<typeof setInterval> | null = null

  private _listeners = new Map<AudioEvent, Set<EventListener<AudioEvent>>>()
  private _stateListeners = new Set<StateListener>()

  constructor(tracks?: Track[]) {
    this._tracks = tracks && tracks.length ? tracks : DEFAULT_TRACKS
  }

  // ─── Getters mirror PulseEngine ─────────────────────────────

  get state(): Readonly<PulseState> {
    return this._state
  }

  get track(): Track {
    const list = this._tracks
    if (!list.length) {
      throw new Error('PulseEngineRN: tracks array is empty')
    }
    const i = this._state.currentTrack
    if (i < 0 || i >= list.length) {
      return list[0]
    }
    return list[i]
  }

  get tracks(): readonly Track[] {
    return this._tracks
  }

  get progress(): number {
    if (this._state.duration === 0) return 0
    return (this._state.currentTime / this._state.duration) * 100
  }

  get eqBars(): readonly number[] {
    return this._eqBars
  }

  get eqAmbientBars(): readonly number[] {
    return this._eqAmbientBars
  }

  // ─── State change subscribers ──────────────────────────────

  onStateChange(cb: StateListener): Unsubscribe {
    this._stateListeners.add(cb)
    return () => {
      this._stateListeners.delete(cb)
    }
  }

  private notifyStateChange(): void {
    for (const cb of this._stateListeners) {
      try {
        cb(this._state)
      } catch {
        // Listener errors must not crash the engine.
      }
    }
  }

  // ─── Event bus ─────────────────────────────────────────────

  subscribe<E extends AudioEvent>(
    event: E,
    cb: EventListener<E>,
  ): Unsubscribe {
    let set = this._listeners.get(event)
    if (!set) {
      set = new Set()
      this._listeners.set(event, set)
    }
    set.add(cb as EventListener<AudioEvent>)
    return () => {
      set?.delete(cb as EventListener<AudioEvent>)
    }
  }

  private emit<E extends AudioEvent>(event: E, payload: EventMap[E]): void {
    const set = this._listeners.get(event)
    if (!set) return
    for (const cb of set) {
      try {
        ;(cb as EventListener<E>)(payload)
      } catch {
        // Listener errors must not crash the engine.
      }
    }
  }

  // ─── Playlist management ───────────────────────────────────

  setAudioTracks(tracks: Track[]): void {
    if (!tracks.length) {
      throw new Error('setAudioTracks: tracks must contain at least one entry')
    }
    this._tracks = tracks
    if (this._state.currentTrack >= tracks.length) {
      this._state = { ...this._state, currentTrack: 0 }
    }
    this.notifyStateChange()
  }

  setAmbientEq(on: boolean): void {
    if (this._state.ambientEq === on) return
    this._state = { ...this._state, ambientEq: on }
    this.notifyStateChange()
  }

  // ─── Audio internals ────────────────────────────────────────

  private async loadSound(): Promise<void> {
    if (this.sound) {
      try {
        await this.sound.unloadAsync()
      } catch {
        // ignore
      }
      this.sound = null
    }
    const track = this.track
    try {
      const { sound } = await Audio.Sound.createAsync(
        { uri: track.src },
        { shouldPlay: false },
        (status) => this.onPlaybackStatusUpdate(status),
      )
      this.sound = sound
    } catch (err) {
      this.emit('error', {
        track,
        reason: 'media-error',
        detail: err,
      } as EventMap['error'])
    }
  }

  private onPlaybackStatusUpdate(status: AVPlaybackStatus): void {
    if (!status.isLoaded) {
      if (status.error) {
        this.emit('error', {
          track: this.track,
          reason: 'media-error',
          detail: status.error,
        } as EventMap['error'])
      }
      return
    }
    const next: PulseState = {
      ...this._state,
      isPlaying: status.isPlaying,
      currentTime: (status.positionMillis ?? 0) / 1000,
      duration: (status.durationMillis ?? 0) / 1000,
    }
    const changed =
      next.isPlaying !== this._state.isPlaying ||
      next.currentTime !== this._state.currentTime ||
      next.duration !== this._state.duration
    if (changed) {
      this._state = next
      this.notifyStateChange()
    }
    if (status.didJustFinish && !status.isLooping) {
      this.next()
    }
  }

  private startEqLoop(): void {
    if (this.eqInterval !== null) return
    this.eqInterval = setInterval(() => {
      // Pseudo-FFT: synthetic 4-bar bouncing pattern. Replace with
      // react-native-audio-api AnalyserNode in a subsequent patch.
      const t = Date.now() / 200
      this._eqBars[0] = 0.4 + 0.6 * Math.abs(Math.sin(t))
      this._eqBars[1] = 0.4 + 0.6 * Math.abs(Math.sin(t + 1))
      this._eqBars[2] = 0.4 + 0.6 * Math.abs(Math.sin(t + 2))
      this._eqBars[3] = 0.4 + 0.6 * Math.abs(Math.sin(t + 3))
    }, 1000 / 30)
  }

  private stopEqLoop(): void {
    if (this.eqInterval !== null) {
      clearInterval(this.eqInterval)
      this.eqInterval = null
    }
    this._eqBars[0] = 0
    this._eqBars[1] = 0
    this._eqBars[2] = 0
    this._eqBars[3] = 0
  }

  // ─── Actions ────────────────────────────────────────────────

  async toggle(): Promise<void> {
    if (!this.sound) {
      await this.loadSound()
    }
    if (!this.sound) return
    if (this._state.isPlaying) {
      try {
        await this.sound.pauseAsync()
      } catch (err) {
        this.emit('error', {
          track: this.track,
          reason: 'play-rejected',
          detail: err,
        } as EventMap['error'])
        return
      }
      this.stopEqLoop()
      this._state = {
        ...this._state,
        isPlaying: false,
        pauseCount: this._state.pauseCount + 1,
      }
      this.notifyStateChange()
      this.emit('pause', { track: this.track, time: this._state.currentTime })
    } else {
      try {
        await this.sound.playAsync()
      } catch (err) {
        this.emit('error', {
          track: this.track,
          reason: 'play-rejected',
          detail: err,
        } as EventMap['error'])
        return
      }
      this.startEqLoop()
      this._state = {
        ...this._state,
        isPlaying: true,
        hasBeenOpened: true,
        isVisible: true,
        playCount: this._state.playCount + 1,
      }
      this.notifyStateChange()
      this.emit('play', { track: this.track, time: this._state.currentTime })
    }
  }

  async loadTrack(i: number): Promise<void> {
    const list = this._tracks
    if (i < 0 || i >= list.length) return
    const previous = this._state.currentTrack
    if (previous === i) return
    const from = previous
    this._state = {
      ...this._state,
      currentTrack: i,
      currentTime: 0,
      duration: 0,
      trackChangeCount: this._state.trackChangeCount + 1,
    }
    this.notifyStateChange()
    this.emit('trackchange', { from, to: i, track: list[i] })
    await this.loadSound()
    if (this._state.isPlaying && this.sound) {
      try {
        await this.sound.playAsync()
      } catch {
        // ignore
      }
    }
  }

  async next(): Promise<void> {
    const i = (this._state.currentTrack + 1) % this._tracks.length
    await this.loadTrack(i)
  }

  async prev(): Promise<void> {
    if (this._state.currentTime > 3) {
      if (this.sound) {
        try {
          await this.sound.setPositionAsync(0)
        } catch {
          // ignore
        }
      }
      return
    }
    const len = this._tracks.length
    const i = (this._state.currentTrack - 1 + len) % len
    await this.loadTrack(i)
  }

  async seek(fraction: number): Promise<void> {
    if (!this.sound) return
    const clamped = Math.max(0, Math.min(1, fraction))
    const targetMs = clamped * this._state.duration * 1000
    try {
      await this.sound.setPositionAsync(targetMs)
    } catch {
      // ignore
    }
  }

  open(): void {
    this._state = { ...this._state, isVisible: true, hasBeenOpened: true }
    this.notifyStateChange()
  }

  async close(): Promise<void> {
    if (this.sound && this._state.isPlaying) {
      try {
        await this.sound.pauseAsync()
      } catch {
        // ignore
      }
    }
    this.stopEqLoop()
    this._state = { ...this._state, isPlaying: false, isVisible: false }
    this.notifyStateChange()
  }

  async dispose(): Promise<void> {
    this.stopEqLoop()
    if (this.sound) {
      try {
        await this.sound.unloadAsync()
      } catch {
        // ignore
      }
      this.sound = null
    }
    this._listeners.clear()
    this._stateListeners.clear()
  }

  fmt(seconds: number): string {
    if (!isFinite(seconds) || seconds < 0) return '0:00'
    const m = Math.floor(seconds / 60)
    const s = Math.floor(seconds % 60)
    return `${m}:${s < 10 ? '0' : ''}${s}`
  }
}

// ─── Singleton (mirrors the web engine-singleton) ─────────────

let sharedEngine: PulseEngineRN | null = null

export function getSharedEngineRN(): PulseEngineRN {
  if (!sharedEngine) {
    sharedEngine = new PulseEngineRN()
  }
  return sharedEngine
}

export function setSharedEngineRN(engine: PulseEngineRN): void {
  sharedEngine = engine
}

// Suppress unused import warning when ErrorReason isn't directly used
// in this file (it's re-exported via the public API and used in
// EventMap['error'] type narrowing).
export type { ErrorReason }
